version: "3.9"
services:
  remote:
    build: ./remotesrv
    ports:
      - "50051:50051"
      - "5000:5000"
    expose:
      - "50051"
      - "5000"
    volumes:
      - type: bind
        source: ./dbs/remote
        target: /var/remotes
    networks:
      - backend
  follower:
    depends_on:
      - "remote"
    build: .
    command: ["sql-server", '--read-only',  "-l", "trace", "--host", "0.0.0.0"]
    ports:
      - "3307:3306"
    expose:
      - "3306"
    working_dir: /var/dbs/follower
    volumes:
      - type: bind
        source: ./dbs/follower/.dolt
        target: /var/dbs/follower/.dolt
    networks:
      - backend
  leader:
    depends_on:
      - "remote"
    build: .
    ports:
      - "3308:3306"
    expose:
      - "3306"
    working_dir: /var/dbs/leader
    volumes:
      - type: bind
        source: ./dbs/leader/.dolt
        target: /var/dbs/leader/.dolt
    networks:
      - backend

networks:
  backend:
    driver: bridge
